src/parsing/include/antioch/species_ascii_parsing.h

A small bug with very embarrassing consequences.  The required informations sanity check was never triggered...
Let's note that the very same fix will be inserted in PR #88, as the name of the files are changed.
This PR will be merged tonight.

Sanity check was bugged, not switchable

---

src/Makefile.am
src/parsing/include/antioch/read_reaction_set_data.h
src/parsing/include/antioch/read_reaction_set_data_xml.h

This header got removed in #72 and we need it for backward compatibility. Note I've used the `#warning` is not standard, but seems to be accepted, so far. We'll see what clang says. Would also like to see what Intel says. I'm open to other suggestions, but at least wanted a warning printed at compile time to clue the user in as to what the not-deprecated header is.

Xml header fix

---

src/Makefile.am
src/diffusion/include/antioch/molecular_binary_diffusion.h
src/kinetics/include/antioch/falloff_reaction.h
src/kinetics/include/antioch/falloff_threebody_reaction.h
src/kinetics/include/antioch/lindemann_falloff.h
src/kinetics/include/antioch/reaction.h
src/kinetics/include/antioch/reaction_enum.h
src/kinetics/include/antioch/reaction_parsing.h
src/kinetics/include/antioch/reaction_set.h
src/kinetics/include/antioch/threebody_reaction.h
src/kinetics/include/antioch/troe_falloff.h
src/parsing/include/antioch/chemkin_parser.h
src/parsing/include/antioch/read_reaction_set_data.h
src/thermal_conduction/include/antioch/kinetics_theory_thermal_conductivity.h
src/thermal_conduction/include/antioch/rotational_relaxation.h
src/viscosity/include/antioch/kinetics_theory_viscosity.h
test/Makefile.am
test/ascii_parser_unit.C
test/lindemann_falloff_threebody_unit.C
test/lindemann_falloff_unit.C
test/parsing_chemkin.C
test/troe_falloff_threebody_unit.C
test/troe_falloff_unit.C

This one is branched off the **kinetics parsing** PR, it is not mergeable with the **Conditions reac** branch, and any daughter branch (thus **opt transport** and **opt kin on transport**).
Because it starts to be difficult to understand where what goes in what order, here is a more beautiful version (and full) of all the PRs.
Thus to be merged last.
This PR adds a monstrosity, a kinetics model that is a falloff and a three body process. Fondamentaly what it does is computing the falloff:
using the three-body description of M:
Thus a new ```FalloffThreeBodyReaction``` object that contains everything the ```FalloffReaction``` has and the ```ThreeBodyReaction```.
A slight update of ```Reaction``` and ```ThreeBodyReaction``` was done also.  The vector of coefficients were stored in the …

Falloff three body

---

src/transport/include/antioch/wilke_transport_evaluator.h

I don't really know where to put that one, but since I'm considering one change to be a bugfix, I'll put it here.  How do we make master aware of this?
The change is in the ```WilkeTransportEvaluator```, there was two places (l. 375 & 382) where we recovered some ```ChemicalMixture``` method from the mixture associated to the viscosity.  The problem is that ```TransportMixture``` do not have those method (enough method duplication), thus this might end up as a compile-time error if you want a ```TransportMixture``` with your viscosity.
So now all the mixture-related things are managed by the ```WilkeTransportMixture```, which ended up in a few simplifications with the bugfix.

Better use of _mixture, now it's in charge of all the mixture related

---

src/kinetics/include/antioch/reaction_set.h

it decreases the index of all following reactions.
If for some reason you have a map of the reactions, this method requires to
update it, Antioch doesn't, so we're cool here.
This is the commit message, says pretty much all.
This method is needed for any purging of reactions.  For instance in PINC I want some system to be in stationary state, thus I need every molecule to have a chemical loss and a chemical production rate. This method enable to automatically modify by pruning the reaction set to avoid well species.

capability to remove a reaction

---

src/parsing/include/antioch/read_reaction_set_data.h
src/parsing/include/antioch/species_parsing.h
src/utilities/include/antioch/antioch_asserts.h

Without a do_once test (and some cerr->cout switches), the verbosity in parallel GRINS runs was unbearable.

Add antioch_do_once for warnings

---

src/parsing/include/antioch/chemkin_parser.h

This clears the last compiler warnings when compiling GRINS with Antioch.

Clear unused variable warnings from chemkin parser

---

src/kinetics/include/antioch/arrhenius_rate.h
src/kinetics/include/antioch/berthelot_rate.h
src/kinetics/include/antioch/berthelothercourtessen_rate.h
src/kinetics/include/antioch/constant_rate.h
src/kinetics/include/antioch/hercourtessen_rate.h
src/kinetics/include/antioch/kinetics_enum.h
src/kinetics/include/antioch/kinetics_parsing.h
src/kinetics/include/antioch/kinetics_type.h
src/kinetics/include/antioch/kooij_rate.h
src/kinetics/include/antioch/photochemical_rate.h
src/kinetics/include/antioch/reaction.h
src/kinetics/include/antioch/reaction_enum.h
src/kinetics/include/antioch/reaction_parsing.h
src/kinetics/include/antioch/reaction_set.h
src/kinetics/include/antioch/troe_falloff.h
src/kinetics/include/antioch/vanthoff_rate.h
src/parsing/include/antioch/read_reaction_set_data.h
src/parsing/include/antioch/xml_parser.h
src/utilities/include/antioch/antioch_asserts.h
src/utilities/include/antioch/string_utils.h
src/utilities/include/antioch/vector_utils.h
src/utilities/include/antioch/vector_utils_decl.h
test/kinetics_regression.C
test/kinetics_settings_unit.C
test/photochemical_rate_unit.C

It'a work still in progress, but as feedback is really wanted, the whole thing will come to life before your eyes.  There's no [DO NOT MERGE] tag so here's a nice question one just to show there's more to it than meets the eye.
So the idea here is to be able to specify in an input file parameters we want to be perturbed, therefore reset.  Human-friendliness requires to have a string-to-parameter map, here's how it goes.
Below the kinetics part, the transport part should be easy to do already, but it's worth to go through it after the kinetics done, so we are comprehensive (same comment for thermo).
A reaction has two levels, the chemical process and the kinetics model.  The XML parser already has string keywords for the parameters, ChemKin format is hard-coded so there's very little need …

Resetting a specific parameter declared in input file

---

src/diffusion/include/antioch/molecular_binary_diffusion.h
src/parsing/include/antioch/ascii_parser.h
src/viscosity/include/antioch/kinetics_theory_viscosity.h

This is a very important bug fix: in the ascii parser, I forgot to update the transport mass definition when we switched to SI units (or got mingled in the parsing PR horror).
This corrects this and adds a few optimizations/constant values management upgrade in the viscosities and diffusion kinetics theory models.
This PR should be merged as soon as possible.  It will very probably require to update the values for the new test in the PR#141.

Huge bugfix in ASCIIParser (unit change was not updated...)

---

src/diffusion/include/antioch/molecular_binary_diffusion.h
src/thermal_conduction/include/antioch/kinetics_theory_thermal_conductivity_utils.h
src/viscosity/include/antioch/kinetics_theory_viscosity.h
test/wilke_transport_unit.C

- in the reset, the float workaround was missing for the
viscosity, thus the value of the coefficient in front
of the spline was zero
- the printing method prints this coefficient for both diffusion
and viscosity
So this fixes the nan the Wilke evaluator was sending back.  That was the case only for float.
I PR it to the 0.3.0 release as it still qualifies as a bug.

bugfix + printing more verbose

---

configure.ac
m4/common/ax_cxx_static_assert.m4

Useful for some metaprogramming foo in the transport-refactor branch; am therefore setting this to merge into the 0.3.0-release branch. If found, then `ANTIOCH_HAVE_CXX_STATIC_ASSERT` will be defined. The idea is to guard and use `static_assert` to get compiler errors, but have runtime fallback errors if `static_assert` is not there.

Test compiler for static_assert

---

src/diffusion/include/antioch/constant_lewis_diffusivity.h
test/constant_lewis_unit.C

Found this during the documentation pass in #148. This is just embarrassing. Fail.
If your Lewis number not equal to 1, then this affects you. We'll have to update all the GRINS/Antioch regression tests.

Fix for ConstantLewisDiffusivity

---

src/transport/include/antioch/mixture_diffusion.h

Forgot to negate the || to an &&
This showed up in GRINS testing. Since this is a simple fix, I'll merge once Travis is happy.

Fix incorrect logic for DiffusionTrait check

---

src/transport/include/antioch/mixture_diffusion.h
src/transport/include/antioch/wilke_transport_evaluator.h
test/wilke_transport_unit.C

There were compile time issues that I uncovered migrating GRINS. We didn't hit them before because of inadequate test coverage in Antioch. There was a logic error in a `static_assert` and an incorrect calling sequence in `MixtureDiffusion`, both related to the `SpeciesDiffusionBase` models. I've fixed both of those problems and have updated the test so that we exercise these paths now.
I will merge once Travis is happy.
With these fixes, GRINS now compiles and passes `make check` with the non-kinetics-theory based transport models (on my [antioch-0.3.0 branch](https://github.com/pbauman/grins/tree/antioch-0.3.0)). I'd like to get the kinetics theory models in there too, but I think this may be the last PR before the 0.3.0 release of Antioch.

Fixes for MixtureDiffusion/SpeciesDiffusionBase Interactions

---

src/thermo/include/antioch/nasa_mixture.h

This should be slightly more helpful than the segfault that
@beanSnippet found in that case.

Assert that the curve fit requested is not NULL

---

src/transport/include/antioch/mixture_averaged_transport_evaluator.h
test/wilke_transport_unit.C

I just went ahead and did this since it was easy (and easier to use MASS_FLUX_MASS_FRACTION on the GRINS side). Compared favorably to Cantera.

Other MixtureAveraged Diffusivity Mixing Rules

---

configure.ac
src/utilities/include/antioch/default_filename.h

Before this PR, `DefaultFilename` always pointed toward the source tree of Antioch for the default data files, with nothing able to point to the install tree. This is fine if you always have the source tree lying around, but this is a restrictive assumption. Here, we rename `DefaultFilename` to `DefaultSourceFilename` (with a typedef for `DefaultFilename` for backward compatibility) and add `DefaultInstallFilename`.
I'd talked about this with @roystgnr in IM a week or two ago and we'd settled on something like this PR.

Setup Default Filenames for Install Tree

---

configure.ac
src/parsing/include/antioch/xml_parser.h
src/parsing/src/read_reaction_set_data.C
src/parsing/src/xml_parser.C
test/Makefile.am
test/fail_parsing_xml_1.sh.in
test/fail_parsing_xml_2.sh.in
test/input_files/fail_parsing_1.xml
test/input_files/fail_parsing_2.xml
test/input_files/test_parsing.xml
test/parsing_xml.C
test/parsing_xml.sh.in

Replaces #174. The only changes I made were to the last commit where I shortened the XML files to only have the failing reaction (and added a comment about what we were testing).

XML Parser Updates

---

src/Makefile.am
src/parsing/src/xml_parser.C
src/utilities/include/antioch/string_utils.h
src/utilities/src/string_utils.C
test/Makefile.am
test/standard_unit/string_utils_test.C

Adds a new `split_string` that will ignore *any* of the delimiter characters (and is much shorter code than the `SplitString` function). Also added `string_to_T` function for converting string to the templated type. Added CppUnit tests for both. Updated `XMLParser` to use the new `split_string` function. Going to use this in fixing the thermo XML parsing (which is currently borked).

New Sting Utilities Functions

---

configure.ac
src/kinetics/include/antioch/reaction.h
src/kinetics/include/antioch/reaction_set.h
src/parsing/include/antioch/chemkin_definitions.h
src/parsing/include/antioch/chemkin_parser.h
src/parsing/include/antioch/nasa_mixture_parsing.h
src/parsing/include/antioch/parser_base.h
src/parsing/include/antioch/parsing_enum.h
src/parsing/include/antioch/xml_parser.h
src/parsing/src/chemkin_parser.C
src/parsing/src/read_reaction_set_data.C
src/parsing/src/xml_parser.C
src/utilities/include/antioch/string_utils.h
test/Makefile.am
test/input_files/orders_chemkin.inp
test/input_files/orders_xml.inp
test/kinetics_partial_order_unit.C
test/kinetics_partial_order_unit.sh.in

This is PR #172 rebased on master. The only thing really changed was I trimmed some of the string utilities to use new functions I introduced in PR #179. `make check` passed all along the way. Going to go ahead and merge since I'll be cleaning up the XML parser anyway. Will open new issues for for the XML cross-compatibility bits. @beanSnippet, would still be glad if you tried out your input on master after this is merged and let us know if you have any problems.
Also, @SylvainPlessis, start using CppUnit for new tests. :) Hopefully @tradowsk will be migrating some of the old one to CppUnit soon.

Kin/orders reactions Rebased

---

src/transport/include/antioch/mixture_averaged_transport_evaluator.h
src/transport/include/antioch/mixture_diffusion.h
src/utilities/include/antioch/antioch_asserts.h
src/viscosity/include/antioch/blottner_viscosity.h
src/viscosity/include/antioch/sutherland_viscosity.h

I found antioch_msg_error misleading (it didn't actually call
antioch_error() ) and not consistent with libmesh_error_msg. :)
This adds the macro and patches up a couple of places where it was
used.

Add antioch_error_msg

---

src/parsing/include/antioch/ascii_parser.h
src/parsing/include/antioch/chemkin_parser.h
src/parsing/include/antioch/xml_parser.h
src/thermo/include/antioch/cea_curve_fit.h
src/thermo/include/antioch/cea_thermo.h
src/thermo/include/antioch/nasa9_curve_fit.h
src/thermo/include/antioch/nasa_curve_fit_base.h
test/Makefile.am
test/Stockmayer_unit.C
test/kinetics_partial_order_unit.C
test/standard_unit/nasa9_curve_fit_test.C
test/wilke_transport_unit.C
test/wilke_transport_vec_unit.C

This is the second part of the NASA curve fit refactoring to facilitate updates/fixes to the parsing. This PR updates the internals of `NASA9CurveFit` to only store 9 coefficients. `NASA9CurveFit` now will only accept coefficients in the "nine form".  `CEACurveFit` only accepts coefficients in the "10 form" and will remap the 10 coefficients to the underlying 9. 
Note this preserves backward compatibility with `CEACurveFit` which has been around awhile. `NASA9CurveFit` is new so we don't need to worry about backward compatibility.
With this form for construction, we can easily apply ASCII (`CEACurveFit`) vs. XML parsing (`NASA9CurveFit`).

NASA Curve Fit Refactor, Part 2

---

src/parsing/include/antioch/xml_parser.h
src/parsing/src/xml_parser.C
src/thermo/include/antioch/nasa7_curve_fit.h
src/thermo/include/antioch/nasa9_curve_fit.h
src/thermo/include/antioch/nasa_curve_fit_base.h
test/Makefile.am
test/input_files/nasa7_thermo_test.xml
test/standard_unit/nasa7_curve_fit_test.C
test/standard_unit/nasa7_thermo_test_base.h
test/standard_unit/nasa9_thermo_test_base.h
test/standard_unit/nasa_mixture_xml_parsing_test.C

Updates the XML parser to support parsing NASA7 coefficients as well. The strategy is to just deduced, based on the `ThermoType` template parameter, whether we're NASA7 or NASA9, and then look for the appropriate keyword.
Most of the lines added here are actually unit testing of both `NASA7CurveFit` and the XML parsing of the NASA7 data. The testing includes parsing the species names from the test XML file instead of supplying them at compile time.
@dsondak, this branch should get your app working with the XML parsing. Please fetch the branch and report any issues you find.

Support XML Parsing of NASA7 Thermodynamics

---

test/arrhenius_rate_deriv.C

This was compiling before, because it was interpreting eta as Ea and
interpreting Ea as R, but it was unnecessarily confusing.

ArrheniusRate depends on Cf, Ea, not on any "eta"

---

CHANGES
Makefile.am
configure.ac
m4/common/gsl_new.m4
src/Makefile.am
src/thermo/include/antioch/stat_mech_thermo.h
src/transport/include/antioch/mixture_diffusion.h
test/gsl_unit/gsl_spliner_test.C
test/gsl_unit/gsl_spliner_test_base.h
test/gsl_unit/gsl_spliner_vec_test.C

Work for 0.4.0 release prep. Cleaned up a couple of warnings, updated, CHANGES, fixed #110 (and a little extra cleanup of gsl_new.m4), and made it so we don't drop the license tool in the distributed tarball (so we get rid of the plethora of output from the license-tool in the builds from tarballs, which would be very confusing to users, probably).

0.4.0 release prep

---

test/berthelothercourtessen_rate_vec_unit.C
test/kooij_rate_vec_unit.C
test/vanthoff_rate_vec_unit.C

For me this fixes "make check" with a newer gcc and Eigen.
Instead of taking relative tolerances w.r.t. exact reaction rates, we
use tol as a minimum denominator.  This prevents false positives when
a reaction rate of 1e-1600 is off by an order of magnitude.
Slightly bumping up the tolerance in kooij_rate_vec_unit is also
necessary to get float to pass for me.

Loosen unit test tolerances

---

.travis.yml

This is a Clang option that's churning out so much output that it's
killing our Travis build with Clang, as seen in #201.  I tested with GCC
and no warnings or errors were emitted using this option.

Turn off -Wdeprecated-declarations

---

src/units/include/antioch/converter.h

When MetaPhysicL is not available, the behavior of Converter should be
unchanged.
When MetaPhysicL is available, it is possible to do mixed type
upgrades (e.g. Converter<long double> * DualNumber<float> ==
Converter<DualNumber<long double> >) based on the CompareTypes
specializations defined there or elsewhere.

MetaPhysicL-enabled upconversion of Converter

---

src/thermo/include/antioch/nasa7_curve_fit.h
src/thermo/include/antioch/nasa9_curve_fit.h
src/thermo/include/antioch/nasa_evaluator.h
test/Makefile.am
test/eigen_unit/nasa_mixture_eigen_test.C
test/nasa_evaluator_unit.C
test/standard_unit/nasa7_curve_fit_test.C
test/standard_unit/nasa7_mixture_vector_test_base.h
test/standard_unit/nasa7_thermo_test_base.h
test/standard_unit/nasa9_curve_fit_test.C
test/standard_unit/nasa9_mixture_vector_test_base.h
test/standard_unit/nasa9_thermo_test_base.h
test/standard_unit/nasa_mixture_valarray_test.C
test/standard_unit/nasa_mixture_xml_parsing_test.C
test/standard_unit/thermo_vector_test_base.h
test/vexcl_unit/nasa_mixture_vexcl_test.C

Builds on #200.
Went down this rabbit hole when removing `CEAThermodynamics` (that's the next PR after this one). The NASAThermoMixture/Evaluators and, therefore, the underlying curve fits, were not exercised in unit tests using vectorized types. This PR makes several fixes to allow that and adds unit testing (in the CppUnit testing framework) for valarray, Eigen, and VexCL types for the NASAThermo. I'll note in the testing, I made sure that the temperatures were such that two different intervals will be need. I'm pretty sure there was a bug in the old `CEAThermodynamics` implementation for vectorized types that we didn't see because we were always in the same temperature interval in the test.
All tests pass for me with Eigen 3.2.8 and VexCL 1.3.3 using GCC 4.9.3. GCC 5.3 has failures in …

NASAThermo Vectorized Evaluations Fix, More Unit Testing

---

test/berthelot_rate_unit.C
test/berthelot_rate_vec_unit.C
test/berthelothercourtessen_rate_unit.C
test/constant_rate_unit.C
test/constant_rate_vec_unit.C
test/hercourtessen_rate_unit.C
test/hercourtessen_rate_vec_unit.C
test/kooij_rate_unit.C
test/rotational_relaxation_vec_unit.C

Mentioned in #201. Also, had to adjust tolerances on some of the
tests. For the berthelothercourtessen_rate_unit, I used @roystgnr's
solution in #198 for comparing very small rates.
I just updated the existing tests because I don't have the time at the moment to sink into converting these to the CppUnit framework. But it would be nice to move that direction.

Fix Clang warnings about std::abs

---

src/transport/include/antioch/mixture_viscosity.h

Looks like we broke this in 19553989; I'd just never used that method
before now.

species_viscosities() type should match

---

test/kinetics_regression_vec.C

This looks like a regression in my version of Eigen and not anything
wrong with Antioch, so I'm disabling that test set.
For future reference, the compilation failure was:
```
/usr/include/eigen3/Eigen/src/Core/Array.h: In instantiation of ‘Eigen::Array<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Array(const T&) [with T = long int; _Scalar = std::valarray<float>; int _Rows = 5; int _Cols = 1; int _Options = 0; int _MaxRows = 5; int _MaxCols = 1]’:
...
/usr/include/eigen3/Eigen/src/Core/Array.h:173:31: error: no matching function for call to ‘Eigen::Array<std::valarray<float>, 5, 1, 0, 5, 1>::_init1(const long int&)’
```

Eigen::Array doesn't currently wrap other vectors?

---

src/parsing/src/blottner_parsing.C

When we ask for Blottner data for a mixture and we don't have Blottner
data for every species in the mixture, we should get an error message,
not a NULL pointer and impending segfault.

Better error handling in Blottner parsing

---

doxygen/Makefile.am

This .sty file encapsulates the extra LaTeX packages we need in
the Doxygen comments. Is now being distributed in the tarball
so we can build the docs from a tarball now.

Distribute antioch.sty

---

examples/Makefile.am

This fixes the problem I hit from #218
We'll probably need to rebase #226 on this.
I think "put everything in share/examples" is the most standard way to go, but I could be talked out of that; I'm willing to settle for any install behavior which does not include "error and die".

Fix make install bug

---

src/thermo/include/antioch/nasa_mixture.h

We only had a const accessor, but we need a non-const accessor if we
want to let users change parameters.
Hopefully this will fix the bug @dsondak found in the new
set_curve_fit_coefficient() method.

Add non-const NASAThermoMixture::curve_fit()

---

test/kinetics_regression_vec.C

This fails on multiple gcc versions and -std= options for me, with
what looks like inadequacies internal to Eigen 3.3.1 and 3.2.6, so I
guess it's not supported.

Disable Eigen Matrix-of-Array tests

---

share/xml_inputs/gri30.xml
src/utilities/src/string_utils.C
test/standard_unit/nasa_mixture_xml_parsing_test.C
test/standard_unit/string_utils_test.C

In putting unit testing in for #240, I was hitting a snag reading NASA7 coefficients from the GRI3 XML shipped with Cantera. After a fun morning/early afternoon, boiled it down to a bug in my implementation of `Antioch::remove_newline_from_strings`; this was particularly bad since the solution was used 5 lines below for a similar problem. *sad face*
I went ahead and added GRI3 XML to the share directory and added a unit test for parsing the NASA coefficients from that XML file.

Bug Fix for Antioch::remove_newline_from_strings, add GRI3 XML to share

---

src/parsing/src/xml_parser.C

While trying to parse the GRi3 XML, There was an error with Troe Reactions with CH2(S) not being recognized as three body because of the extra parenthesis.

Fixed Parsing error for Reactions with species like CH2(S)

---

src/transport/include/antioch/mixture_diffusion.h

This removes an annoying `warning: unused variable ‘n_cols’ [-Wunused-variable]` that I get when building `GRINS` `opt`.

Fix unused variable warning

---

src/parsing/include/antioch/parser_base.h
src/parsing/include/antioch/parsing_enum.h
src/parsing/include/antioch/xml_parser.h
src/parsing/src/xml_parser.C
test/standard_unit/gri30_xml_parsing_test.C
test/standard_unit/nasa_mixture_xml_parsing_test.C

Should be merged after #254.
Closes #251.
Added function that queries the XML file. We just look at the first species and check for the key for NASA7 or NASA9 and error if it's not one of the two. We rely on the subsequent parsing of the thermo during the `read_thermodynamic_data` call to catch inconsistent/mixed use of NASA7 and NASA9. There is unit testing of both NASA7 and NASA9 cases.

Query NASA Curve Fit Type from XML file

---

src/Makefile.am
src/thermo/include/antioch/ideal_gas_micro_thermo.h
src/thermo/include/antioch/ideal_gas_thermo.h
src/thermo/include/antioch/macro_micro_thermo_base.h
test/standard_unit/macro_micro_thermo_test.C

Closes #257.
Functionally, the classes do the same computations, but construction API makes much more sense for the user in `IdealGasThermo` vs `IdealGasMicroThermo`.
I'd like to use this in grinsfem/grins ASAP, so would like to merge quickly.

Add IdealGasThermo, Deprecate IdealGasMicroThermo

---

src/parsing/include/antioch/parsing_enum.h
src/parsing/include/antioch/xml_parser.h
src/parsing/src/xml_parser.C
test/standard_unit/gri30_xml_parsing_test.C

Closes #249.
Implements parsing for the `TransportMixture` object using our XMLParser. Unit tested on GRI 3.0 XML file. I didn't implement unit conversion here, but at least throw an error if the incorrect unit is specified so we don't get any surprises.

XML Parsing for TransportMixture

---

src/parsing/src/blottner_parsing.C

This was sneaky and I only noticed where there was an errant
message of opening the default transport file. We wanted a
TransportMixture, but we grabbed a ChemicalMixture (probably a
copy/paste bug). But TransportMixture has a bunch of default
arguments so a ChemicalMixture was enough to trigger construction
of a TransportMixture with default things. This would've been
frustrating once we tried to do this with species that weren't
in the default transport data file.

Fix grabbing wrong mixture in Blotter data parsing

---

src/parsing/src/species_parsing.C

Recently did a 520 core `GRINS+Antioch` run and got almost 2000 lines of warnings saying that vibrational levels for O were missing.
This fixes that output mess.

Fix redundant warning messages
